github.com:
    users:
        Nstern90:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Nstern90
